;(function(){var dfltPluginCfg={"info":"True"};var dfltGlobalCfg={"site":411548,"log":"logc111","logSSL":"logs1111","domain":"xiti.com","secure":false,"pixelPath":"/hit.xiti","disableCookie":false,"cookieDomain":"","preview":false,"plgs":["Campaigns","Clicks","ClientSideUserId","ContextVariables","IdentifiedVisitor","InternalSearch","OnSiteAds","Page"],"lazyLoadingPath":"","documentLevel":"document","redirect":false};window.ATInternet=window.ATInternet||{};
window.ATInternet.Utils=new function(){function a(b){var g=typeof b;if("object"!==g||null===b)return"string"===g&&(b='"'+b+'"'),String(b);var k,d,f=[],e=b&&b.constructor===Array;for(k in b)b.hasOwnProperty(k)&&(d=b[k],g=typeof d,"function"!==g&&"undefined"!==g&&("string"===g?d='"'+d.replace(/[^\\]"/g,'\\"')+'"':"object"===g&&null!==d&&(d=a(d)),f.push((e?"":'"'+k+'":')+String(d))));return(e?"[":"{")+String(f)+(e?"]":"}")}var b=this;b.cloneSimpleObject=function g(a,d){if("object"!==typeof a||null===
a||a instanceof Date)return a;var f=new a.constructor||a.constructor(),e;for(e in a)a.hasOwnProperty(e)&&(void 0===e||d&&void 0===a[e]||(f[e]=g(a[e])));return f};b.jsonSerialize=function(g){return"undefined"!==typeof JSON&&JSON.stringify?JSON.stringify(g):a(g)};b.jsonParse=function(a){try{if("undefined"!==typeof JSON&&JSON.parse)return JSON.parse(a);var b;b=null===a?a:"string"===typeof a?(new Function("return "+a))():!1;return b}catch(d){return null}};b.arrayIndexOf=function(a,b){return Array.indexOf?
a.indexOf(b):function(a){if(null==this)throw new TypeError;var g=Object(this),e=g.length>>>0;if(0===e)return-1;var c=0;1<arguments.length&&(c=Number(arguments[1]),c!=c?c=0:0!=c&&Infinity!=c&&-Infinity!=c&&(c=(0<c||-1)*Math.floor(Math.abs(c))));if(c>=e)return-1;for(c=0<=c?c:Math.max(e-Math.abs(c),0);c<e;c++)if(c in g&&g[c]===a)return c;return-1}.apply(a,[b])};b.genGuid=function(a){var b=new Date,d=function(a){a-=100*Math.floor(a/100);return 10>a?"0"+a:a};return d(b.getHours())+""+d(b.getMinutes())+
""+d(b.getSeconds())+""+function(a){return Math.floor(Math.random()*Math.pow(10,a))}(a-6)};b.getObjectKeys=function(a){var b=[],d;for(d in a)a.hasOwnProperty(d)&&b.push(d);return b};b.completeFstLevelObj=function(a,b,d){if(a){if(b)for(var f in b)!b.hasOwnProperty(f)||a[f]&&!d||(a[f]=b[f])}else a=b;return a};b.isPreview=function(){return window.navigator&&"preview"===window.navigator.loadPurpose};b.isPrerender=function(a){var k,d=!1,f=["webkit","ms"];if("prerender"===document.visibilityState)k="visibilitychange";
else for(var e=0;e<f.length;e++)"prerender"===document[f[e]+"VisibilityState"]&&(k=f[e]+"visibilitychange");if("undefined"!==typeof k){var c=function(e){a(e);b.removeEvtListener(document,k,c)};b.addEvtListener(document,k,c);d=!0}return d};b.addEvtListener=function(a,b,d){a.addEventListener?a.addEventListener(b,d,!1):a.attachEvent&&a.attachEvent("on"+b,d)};b.removeEvtListener=function(a,b,d){a.removeEventListener?a.removeEventListener(b,d,!1):a.detachEvent&&a.detachEvent("on"+b,d)};b.loadScript=function(a,
b){var d;b=b||function(){};d=document.createElement("script");d.type="text/javascript";d.src=a.url;d.async=!1;d.defer=!1;d.onload=d.onreadystatechange=function(a){a=a||window.event;if("load"===a.type||/loaded|complete/.test(d.readyState)&&(!document.documentMode||9>document.documentMode))d.onload=d.onreadystatechange=d.onerror=null,b(null,a)};d.onerror=function(a,c,l){d.onload=d.onreadystatechange=d.onerror=null;b({msg:"script not loaded",event:a})};var f=document.head||document.getElementsByTagName("head")[0];
f.insertBefore(d,f.lastChild)};b.hashcode=function(a){var b=0;if(0===a.length)return b;for(var d=0;d<a.length;d++)var f=a.charCodeAt(d),b=(b<<5)-b+f,b=b&b;return b};b.setLocation=function(a){var b=a.location;a=window[a.target]||window;b&&(a.location.href=b)}};
var BuildManager=function(a){var b=this,h=function(a,b,e){a="&"+a+"=";return{param:a,paramSize:a.length,str:b,strSize:b.length,truncate:e}},g=function(a,b){var e="",d=0,g=!0,f;for(f in a)if(a.hasOwnProperty(f)){var s=a[f];if(s){var g=!1,q=b-d;if(s.strSize+s.paramSize<q)e+=s.param+s.str,d+=s.strSize+s.paramSize,a[f]=void 0,g=!0;else{s.truncate?(e+=s.param+s.str.substr(0,q),a[f].str=s.str.substr(q,s.strSize-1),a[f].strSize=a[f].str.length):s.strSize+s.paramSize>b&&(a[f].str=a[f].str.substr(0,b-s.paramSize-
1),a[f].strSize=a[f].str.length);break}}else g=!0}return[e,g?null:a]},k=["ati","atc","pdtl","stc","dz"],d=function(c,b,e){var d=function(a){if(a==={})return"";var c=[],b;b={};var e=0,d=!1,l=void 0,f,n,p;for(p in a)if(a.hasOwnProperty(p)){var r=a[p].value;"function"===typeof r&&(r=r());r=r instanceof Array?r.join(a[p].options.separator||","):"object"===typeof r?window.ATInternet.Utils.jsonSerialize(r):"undefined"===typeof r?"undefined":r.toString();a[p].options.encode&&(r=encodeURIComponent(r));var t=
h(p,r,-1<window.ATInternet.Utils.arrayIndexOf(k,p)),e=e+(t.paramSize+t.strSize);if(a[p].options.last)1490<r.length&&r.substr(0,1490),f=p,n=t;else if(b[p]=t,1500<b[p].paramSize+b[p].strSize&&!b[p].truncate){d=!0;l=p;break}}f&&(b[f]=n);b=[b,e,d,l];a=b[0];if(b[2])b=b[3],a=a[b],a.str=a.str.substr(0,1450),a.strSize=1450,e={},e.mherr=h("mherr","1",!1),e[b]=a,c.push(g(e,1500)[0]);else if(b=g(a,1500),null===b[1])c=b[0];else for(c.push(b[0]);null!==b[1];)b=g(a,1500),c.push(b[0]);return c},f="";a.buffer.presentInFilters(b,
"typeHit")||(b=a.buffer.addInFilters(b,"typeHit",["page"]));b=a.buffer.addInFilters(b,"typeHit",["all"]);var p;if(c){b=a.buffer.addInFilters(b,"permanent",!0);b=a.buffer.get(b,!0);for(p in c)c.hasOwnProperty(p)&&(b[p]={value:c[p],options:{}});f=d(b)}else for(p in b=a.buffer.get(b,!0),f=d(b),b)b.hasOwnProperty(p)&&!b[p].options.permanent&&a.buffer.del(p);e&&e(f)},f=function(c){var b=a.getConfig("secure"),e="https:"===document.location.protocol,e=b||e?a.getConfig("logSSL"):a.getConfig("log"),d=a.getConfig("baseURL"),
f=a.getConfig("domain"),g=a.getConfig("pixelPath"),h=a.getConfig("site");(d||e&&f&&g)&&h?c&&c(null,(d?d:(b?"https://":"//")+e+("."+f)+g)+("?s="+h)):c&&c({message:"Config error"})},e=function(a,b,e){f(function(f,g){f?e&&e(f):d(a,b,function(a){var c=[],b=window.ATInternet.Utils.genGuid(13);if(a instanceof Array)if(1===a.length)c.push(g+"&mh=1-2-"+b+a[0]);else for(var d=1;d<=a.length;d++)c.push(g+"&mh="+d+"-"+a.length+"-"+b+a[d-1]);else c.push(g+a);e&&e(null,c)})})};b.send=function(c,d){e(c,d,function(c,
e){if(c)a.triggers.emit("Tracker:Hit:Build:Error",{msg:c.message});else for(var d=0;d<e.length;d++)b.sendUrl(e[d])})};b.sendUrl=function(c){var b=function(c,b){return function(){return function(e){a.triggers.emit(c,{details:{hit:b}})}}()},e=new Image;e.onload=b("Tracker:Hit:Sent:Ok",c,!1);e.onerror=b("Tracker:Hit:Sent:Error",c,!1);e.src=c}},TriggersManager=function(){function a(a,b,f){for(var e=[],c=0;c<a.length;c++)a[c].callback(b,f),a[c].singleUse||e.push(a[c]);return e}function b(a,d,f,e){var c=
a.shift();if("*"===c)return d["*"]=d["*"]||[],d["*"].push({callback:f,singleUse:e}),d["*"].length-1;if(0===a.length)return b([c,"*"],d,f,e);d["*"]=d["*"]||[];d[c]=d[c]||{};return b(a,d[c],f,e)}function h(b,d,f,e){var c=d.shift();"*"!==c&&(0===d.length?h(b,[c,"*"],f,e):f[c]&&(f[c]["*"]=a(f[c]["*"],b,e),h(b,d,f[c],e)))}var g={};this.on=function(a,d,f){f=f||!1;return b(a.split(":"),g,d,f)};this.emit=function(b,d){g["*"]&&(g["*"]=a(g["*"],b,d));h(b,b.split(":"),g,d)}},PluginsManager=function(a){var b=
{},h={},g=0,k={},d=0,f=this.load=function(c,d){"function"===typeof d?"undefined"===typeof a.getConfig.plgAllowed||0===a.getConfig.plgAllowed.length||-1<a.getConfig.plgAllowed.indexOf(c)?(b[c]=new d(a),h[c]&&b[c]&&(h[c]=!1,g--,b[c+"_ll"]&&e(c+"_ll"),0===g&&a.triggers.emit("Tracker:Plugin:Lazyload:File:Complete",{msg:"LazyLoading triggers are finished"})),a.triggers.emit("Tracker:Plugin:Load:"+c+":Ok",{})):a.triggers.emit("Tracker:Plugin:Load:"+c+":Error",{msg:"Plugin not allowed",details:{}}):a.triggers.emit("Tracker:Plugin:Load:"+
c+":Error",{msg:"not an object",details:{obj:d}});return a},e=this.unload=function(c){b[c]?(b[c]=void 0,a.triggers.emit("Tracker:Plugin:Unload:"+c+":Ok",{})):a.triggers.emit("Tracker:Plugin:Unload:"+c+":Error",{msg:"not a known plugin"});return a},c=this.isLazyloading=function(a){return a?!0===h[a]:0!==g},l=function(a){return t(a)?(n(a),!0):!1},n=function(c){h[c]=!0;g++;ATInternet.Utils.loadScript({url:a.getConfig("lazyLoadingPath")+c+".js"})},t=function(a){return!b[a]&&!c(a)&&(b[a+"_ll"]?!0:!1)},
r=function(a){k[a]?k[a]++:k[a]=1;d++};this.isExecWaitingLazyloading=function(){return 0!==d};a.exec=this.exec=function(e,f,q,g){var l=null,h=function(a,c,e,d){c=c.split(".");b[a]&&b[a][c[0]]&&(l=1<c.length&&b[a][c[0]][c[1]]?b[a][c[0]][c[1]].apply(b[a],e):b[a][c[0]].apply(b[a],e));d&&d(l)},u=function(c,b,e,f){r(c);a.onTrigger("Tracker:Plugin:Load:"+c+":Ok",function(){h(c,b,e,function(b){k[c]--;d--;0===d&&a.triggers.emit("Tracker:Plugin:Lazyload:Exec:Complete",{msg:"All exec waiting for lazyloading are done"});
f&&f(b)})},!0)};t(e)?(u(e,f,q,g),n(e)):c(e)?u(e,f,q,g):h(e,f,q,g)};this.waitForDependencies=function(c,e){var d=function(a){for(var c={mcount:0,plugins:{}},e=0;e<a.length;e++)b.hasOwnProperty(a[e])||(c.mcount++,c.plugins[a[e]]=!0);return c}(c);if(0===d.mcount)e();else for(var f in d.plugins)d.plugins.hasOwnProperty(f)&&(a.onTrigger("Tracker:Plugin:Load:"+f,function(a,c){var b=a.split(":"),f=b[3];"Ok"===b[4]&&(d.plugins[f]=!1,d.mcount--,0===d.mcount&&e())},!0),l(f))};this.init=function(){for(var c in a.pluginProtos)a.pluginProtos.hasOwnProperty(c)&&
f(c,a.pluginProtos[c])}},BufferManager=function(){var a={};this.set=function(b,h,d){d=d||{};d.typeHit=d.typeHit||["page"];a[b]={value:h,options:d}};var b=function(a,b,d){return(a=window.ATInternet.Utils.cloneSimpleObject(a[b]))&&!d?a.value:a},h=function k(b,f){if(!(b&&f instanceof Array&&b instanceof Array))return[];if(0===b.length)return f;var e=b[0],c,l=[],n=window.ATInternet.Utils.cloneSimpleObject(b);n.shift();for(var h=0;h<f.length;h++)if("object"!==typeof e[1])a[f[h]]&&a[f[h]].options[e[0]]===
e[1]&&l.push(f[h]);else{c=e[1].length;for(var r=0;r<c;r++)if(a[f[h]]&&a[f[h]].options[e[0]]instanceof Array&&0<=window.ATInternet.Utils.arrayIndexOf(a[f[h]].options[e[0]],e[1][r])){l.push(f[h]);break}}return k(n,l)};this.get=function(k,d){var f={};if("string"===typeof k)f=b(a,k,d);else for(var e=h(k,window.ATInternet.Utils.getObjectKeys(a)),c=0;c<e.length;c++)f[e[c]]=b(a,e[c],d);return f};this.presentInFilters=function d(a,b){return a&&0!==a.length?a[0][0]===b?!0:d(a.slice(1),b):!1};this.addInFilters=
function f(a,c,b,h){if(!a||0===a.length)return h?[]:[[c,b]];var t=a[0][0],r=a[0][1];t===c&&(r instanceof Array&&!(-1<window.ATInternet.Utils.arrayIndexOf(r,b[0]))&&r.push(b[0]),h=!0);return[[t,r]].concat(f(a.slice(1),c,b,h))};this.del=function(b){a[b]=void 0};this.clear=function(){a={}}},Tag=function(a,b,h){b=b||{};var g=this;g.version="5.2.2";var k=window.ATInternet.Utils.cloneSimpleObject(b);g.triggers=new TriggersManager(g);g.emit=g.triggers.emit;g.onTrigger=g.triggers.on;var d=window.ATInternet.Utils.cloneSimpleObject(dfltGlobalCfg)||
{},f;for(f in a)d[f]=a[f];g.getConfig=function(a){return d[a]};g.setConfig=function(a,c,b){void 0!==d[a]&&b||(g.emit("Tracker:Config:Changed:"+a,{details:{bef:d[a],aft:c}}),d[a]=c)};g.configPlugin=function(a,c,b){d[a]=d[a]||{};for(var f in c)void 0===d[a][f]&&(d[a][f]=c[f]);b&&(b(d[a]),g.onTrigger("Tracker:Config:Changed:"+a,function(a,c){b(c.details.aft)}));return d[a]};g.getContext=function(a){return k[a]};g.setContext=function(a,c){g.emit("Tracker:Context:Changed:"+a,{details:{bef:k[a],aft:c}});
k[a]=c};g.delContext=function(a,c){g.emit("Tracker:Context:Deleted:"+a+":"+c,{details:{key1:a,key2:c}});if(a)k.hasOwnProperty(a)&&(c?k[a]&&k[a].hasOwnProperty(c)&&(k[a][c]=void 0):k[a]=void 0);else if(c)for(var b in k)k[b]&&k[b].hasOwnProperty(c)&&(k[b][c]=void 0)};g.plugins=new PluginsManager(g);g.buffer=new BufferManager(g);g.setParam=g.buffer.set;g.getParams=function(a){return g.buffer.get(a,!1)};g.getParam=g.buffer.get;g.delParam=g.buffer.del;g.builder=new BuildManager(g);g.sendHit=g.builder.send;
g.sendUrl=g.builder.sendUrl;g.setParam("ts",function(){return(new Date).getTime()},{permanent:!0,typeHit:["all"]});g.getConfig("disableCookie")&&g.setParam("idclient","xxxxxx-NO",{permanent:!0,typeHit:["all"]});g.plugins.init();g.emit("Tracker:Load",{details:{tracker:g}});Tag.prototype.instances.push(g);h&&h(g)};Tag.prototype.instances=[];Tag.prototype.pluginProtos={};
Tag.prototype.addPlugin=function(a,b){b=b||window.ATInternet.Tracker.Plugins[a];if(!this.pluginProtos[a]){this.pluginProtos[a]=b;for(var h=0;h<this.instances.length;h++)this.instances[h].plugins.load(a,b)}};Tag.prototype.delPlugin=function(a){if(this.pluginProtos[a]){this.pluginProtos[a]=void 0;for(var b=0;b<this.instances.length;b++)this.instances[b].plugins.unload(a)}};
(function(a,b){a.ATInternet=a.ATInternet||{};a.ATInternet.Tracker=a.ATInternet.Tracker||{};a.ATInternet.Tracker.Tag=Tag;a.ATInternet.Tracker.Plugins=a.ATInternet.Tracker.Plugins||{}})(window);
}).call(window);;(function(){var dfltPluginCfg={"lifetime":30,"lastPersistence":true,"listEventsForExec":[],"domainAttribution":true,"info":"True"};var dfltGlobalCfg={"visitLifetime":30,"redirectionLifetime":30};window.ATInternet.Tracker.Plugins.Campaigns=function(a){a.setConfig("visitLifetime",dfltGlobalCfg.visitLifetime,!0);a.setConfig("redirectionLifetime",dfltGlobalCfg.redirectionLifetime,!0);var b={},h,g;a.configPlugin("Campaigns",dfltPluginCfg||{},function(a){b=a});var k,d,f,e,c,l,n,t,r,p,s,q,E,w=function(c,b,d){var e=null;a.plugins.exec(c,b,d,function(a){e=a});return e},v=function(a,c){return w("Cookies",a,c)},u=function(a,c){return w("Utils",a,c)},A=function(a,c){var b=v(g,[[a]]);if(null!==b)return!("object"!==
typeof b||b instanceof Array);v(h,[a,{},c]);return!0},G=function(c,b){var d=a.getContext("campaigns")||{};d[c]=b;a.setContext("campaigns",d)},O=function(w){h="set"+(b.domainAttribution?"":"Private");g="get"+(b.domainAttribution?"":"Private");k=v(g,[["atredir","gopc"]]);d=v(g,[["atredir","gopc_err"]]);f=v(g,[["atredir","camp"]]);v("del",[["atredir","gopc"]]);v("del",[["atredir","gopc_err"]]);v("del",[["atredir","camp"]]);e=v(g,[["atsession","histo_camp"]]);c=v(g,[["atreman","camp"]]);l=v(g,[["atreman",
"date"]]);var x=u("getLocation",[]);n=u("getQueryStringValue",["xtor",x]);t=u("getQueryStringValue",["xtdt",x]);r=u("getQueryStringValue",["xts",x]);p=a.getContext("forcedCampaign");s=!!a.getConfig("redirect");if(q=n&&t&&r?!0:!1)x=(new Date).getTime()/6E4,E=!s&&r!==a.getConfig("site")||0>x-t||x-t>=a.getConfig("visitLifetime")?!0:!1;x=p||f||n;s&&x&&A("atredir",{path:"/",end:a.getConfig("redirectionLifetime")})&&(v(h,[["atredir","camp"],x]),v(h,[["atredir","gopc"],p?!1:f?k:q?!0:!1]),v(h,[["atredir",
"gopc_err"],p?!1:f?d:E?!0:!1]));!s&&c&&(G("xtor",c),x=(new Date).getTime()/36E5,x=Math.floor(x-l),G("roinbh",0<=x?x:0));s||(x=void 0,x=f?k?p||x:p||f:q?p||x:p||n||x,e&&e instanceof Array&&-1<e.indexOf(x)&&(x=void 0),x&&G("xto",x));if(!s&&!p){var K;f?d&&(K=f):E&&(K=n);K&&G("pgt",K)}s||!(K=f?p||f:p||n||void 0)||!p&&!f&&q&&E||!p&&f&&k&&d||((!e||e instanceof Array&&0>e.indexOf(K))&&A("atsession",{path:"/",session:60*a.getConfig("visitLifetime")})&&v(h,[["atsession","histo_camp"],e&&e.push(K)?e:[K]]),c&&
!b.lastPersistence||!A("atreman",{path:"/",session:86400*b.lifetime})||(v(h,[["atreman","camp"],K]),v(h,[["atreman","date"],(new Date).getTime()/36E5])));a.emit("Campaigns:"+w)};(function(){var c=["Cookies","Utils"];if(-1===ATInternet.Utils.arrayIndexOf(a.getConfig("plgs"),"BackwardCompat"))a.plugins.waitForDependencies(c,function(){O("process2:done")});else a.onTrigger("BackCampaigns:process2:done",function(b,d){a.plugins.waitForDependencies(c,function(){O("process1:done")})},!0)})()};window.ATInternet.Tracker.Tag.prototype.addPlugin("Campaigns");
}).call(window);;(function(){var dfltPluginCfg={"info":"True"};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.Clicks=function(a){var b=function(a){var b="";switch(a){case "exit":b="S";break;case "download":b="T";break;case "action":b="A";break;case "navigation":b="N"}return b},h=function(b){var d=b.name;a.exec("Utils","manageChapters",[b,"chapter",3],function(a){d=a+(d?d:"")});return d},g=function(g){var d={p:h(g),s2:g.level2||"",click:b(g.type)||""},f=a.getContext("page")||{};d.pclick=h(f);d.s2click=f.level2||"";g.customObject&&a.exec("Utils","customObjectToString",[g.customObject],
function(a){d.stc=a});a.sendHit(d,[["typeHit",["click"]]])};a.click={};a.clickListener=this.clickListener={};a.click.send=this.send=function(b){var d=!0;a.plugins.exec("TechClicks","manageClick",[b.elem],function(a){d=a});g(b);return d};a.clickListener.send=this.clickListener.send=function(b){if(b.elem){var d;a.plugins.exec("TechClicks","isFormSubmit",[b.elem],function(a){d=a?"submit":"click"});ATInternet.Utils.addEvtListener(b.elem,d,function(d){a.plugins.exec("TechClicks","manageClick",[b.elem,
d]);g(b)})}};a.click.set=this.set=function(g){a.dispatchSubscribe("click");a.setContext("click",{name:h(g),level2:g.level2||"",customObject:g.customObject});a.setParam("click",b(g.type)||"",{typeHit:["click"]})};a.click.onDispatch=this.onDispatch=function(){var b={typeHit:["click"]};a.setParam("p",a.getContext("click").name,b);a.setParam("s2",a.getContext("click").level2,b);var d=a.getContext("click").customObject;d&&a.setParam("stc",d,{typeHit:["click"],encode:!0});d=a.getContext("page")||{};a.setParam("pclick",
h(d),b);a.setParam("s2click",d.level2||"",b);a.sendHit(null,[["typeHit",["click"]]]);a.setContext("click",void 0)}};window.ATInternet.Tracker.Tag.prototype.addPlugin("Clicks");
}).call(window);;(function(){var dfltPluginCfg={"clientSideMode":"required","userIdCookieDuration":397,"userIdExpirationMode":"fixed","info":"True"};var dfltGlobalCfg={};(function(){window.ATInternet.Tracker.Plugins.ClientSideUserId=function(a){var b={},h=void 0,g=null;a.configPlugin("ClientSideUserId",dfltPluginCfg||{},function(a){b=a});var k=function(){h=a.getContext("userIdentifier");a.exec("Cookies","get",["atuserid"],function(a){g=a})},d=function(c,b){a.setParam("idclient",c,{permanent:!0,typeHit:["all"]});f(c,b)},f=function(c,d){if("relative"===b.userIdExpirationMode||"fixed"===b.userIdExpirationMode&&null===g){var e=new Date;e.setTime(e.getTime()+864E5*b.userIdCookieDuration);
a.exec("Cookies","set",["atuserid",c,{end:e,path:"/"}]);a.exec("Cookies","get",["atuserid",!0],function(b){d||c===b||a.setParam("idclient",c+"-NO",{permanent:!0,typeHit:["all"]})})}},e=function(){var a=!1;if("required"===b.clientSideMode){var d=navigator.userAgent;if(/Safari/.test(d)&&!/Chrome/.test(d)||/iPhone|iPod|iPad/.test(d))a=!0}else"always"===b.clientSideMode&&(a=!0);return a};a.plugins.waitForDependencies(["Cookies"],function(){k();if(e()){var a="",b=!1;"undefined"!==typeof h?(a=h,b=!0):a=
null!==g?g:ATInternet.Utils.genGuid(13);d(a,b)}});a.clientSideUserId={};a.clientSideUserId.set=function(a){e()&&d(a,!0)}};window.ATInternet.Tracker.Tag.prototype.addPlugin("ClientSideUserId")})();
}).call(window);;(function(){var dfltPluginCfg={"domainAttribution":true,"info":"True"};var dfltGlobalCfg={"redirectionLifetime":30};window.ATInternet.Tracker.Plugins.ContextVariables=function(a){var b="",h=null,g="",k="",d={};a.configPlugin("ContextVariables",dfltPluginCfg||{},function(a){d=a});a.setConfig("redirectionLifetime",dfltGlobalCfg.redirectionLifetime,!0);var f=function(c,b,d){var e=null;a.plugins.exec(c,b,d,function(a){e=a});return e},e=function(a,c){return f("Utils",a,c)},c=function(c,b){var d=null;a.plugins.exec("Cookies",c,b,function(a){d=a});return d},l=function(){a.setParam("hl",function(){var a=new Date;return a.getHours()+
"x"+a.getMinutes()+"x"+a.getSeconds()},{permanent:!0,typeHit:["all"]})},n=function(a){var c="",c="acc_dir"===b?"":b?b:"acc_dir"===h?"":h?h:a.referrer;return c.replace(/[<>]/g,"").substring(0,1600).replace(/&/g,"$")};a.plugins.waitForDependencies(["Cookies","Utils"],function(){g="set"+(d.domainAttribution?"":"Private");k="get"+(d.domainAttribution?"":"Private");var f=e("getLocation",[]);b=e("getQueryStringValue",["xtref",f]);if(a.getConfig("redirect")){var f=e("getDocumentLevel",[]),f=b||f.referrer||
"acc_dir",r;if(r=f){r={path:"/",end:a.getConfig("redirectionLifetime")};var p=c(k,[["atredir"]]);null!==p?r=!("object"!==typeof p||p instanceof Array):(c(g,["atredir",{},r]),r=!0)}r&&c(g,[["atredir","ref"],f])}else{h=c(k,[["atredir","ref"]]);c("del",[["atredir","ref"]]);a.setParam("vtag",a.version,{permanent:!0,typeHit:["all"]});a.setParam("ptag","js",{permanent:!0,typeHit:["all"]});f="";try{f+=window.screen.width+"x"+window.screen.height+"x"+window.screen.pixelDepth+"x"+window.screen.colorDepth}catch(s){}a.setParam("r",
f,{permanent:!0,typeHit:["all"]});f="";window.innerWidth?f+=window.innerWidth+"x"+window.innerHeight:document.body.offsetWidth&&(f+=document.body.offsetWidth+"x"+document.body.offsetHeight);a.setParam("re",f,{permanent:!0,typeHit:["all"]});l();a.setParam("lng",navigator.language||navigator.userLanguage,{permanent:!0,typeHit:["all"]});f=window.ATInternet.Utils.genGuid(13);a.setParam("idp",f,{permanent:!0,typeHit:["page","clickzone"]});a.setParam("jv",navigator.javaEnabled()?"1":"0",{typeHit:["page"]});
f=e("getDocumentLevel",[]);a.setParam("ref",n(f),{permanent:!0,last:!0,typeHit:["page"]})}})};window.ATInternet.Tracker.Tag.prototype.addPlugin("ContextVariables");
}).call(window);;(function(){var dfltPluginCfg={"info":"False"};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.Cookies=function(a){var b={},h=this.getCookie=function(c){return!a.getConfig("disableCookie")&&c&&"string"===typeof c&&(c=RegExp("(?:^| )"+c+"=([^;]+)").exec(document.cookie)||null)?decodeURIComponent(c[1]):null},g=this.setCookie=function(c,b,d){if(!a.getConfig("disableCookie")&&c&&"string"===typeof c&&"string"===typeof b){var e=a.getConfig("cookieDomain");c=c+"="+encodeURIComponent(b);if(d){b=d.end;var f=d.domain,l=d.path;d=d.secure;c+=b?"function"===typeof b.toGMTString?
";expires="+b.toGMTString():"number"===typeof b?";max-age="+b.toString():"":"";c=c+(e||f?";domain="+(f?f:e):"")+(l&&"string"===typeof l?";path="+l:"");c+=d&&"boolean"===typeof d?";secure":""}document.cookie=c;return!0}return null},k=function(a){var c=null;(a=h(a))&&(c=ATInternet.Utils.jsonParse(a));return c},d=function(a){return g(a.name,ATInternet.Utils.jsonSerialize(a),a.options)?a:null},f=function(a,c,e){var f=null;if(!e&&b[a])f=b[a];else if(f=k(a))f.options.session&&d(f),b[a]=f;return f?c?(a=
null,!f||"object"!==typeof f.val||f.val instanceof Array||void 0===f.val[c]||(a=f.val[c]),a):f.val:null},e=function(a,c,e,f){var l=null;if(c){if(l=k(a))f=l,!f||"object"!==typeof f.val||f.val instanceof Array?l=null:(f.val[c]=e,l=f),l&&(l=d(l))}else c=f=f||{},f={},f.name=a,f.val=e,c.session&&"number"===typeof c.session&&(c.end=c.session),f.options=c,l=d(f);l&&(b[a]=l);return l?l.val:null},c=function(a,c){c?e(a,c,void 0):(b[a]=void 0,g(a,"",{end:0}))},l=this.get=function(a,c){c=c||!1;return a instanceof
Array&&2===a.length?f(a[0],a[1],c):f(a,void 0,c)};this.getPrivate=function(c,b){b=b||!1;c instanceof Array?c[0]+=a.getConfig("site"):c+=a.getConfig("site");return l(c,b)};var n=this.set=function(a,c,b){return a instanceof Array?e(a[0],a[1],c):e(a,null,c,b)};this.setPrivate=function(c,b,d){c instanceof Array?c[0]+=a.getConfig("site"):c+=a.getConfig("site");return n(c,b,d)};var t=this.del=function(a){return a instanceof Array?c(a[0],a[1]):c(a)};this.delPrivate=function(c){c instanceof Array?c[0]+=a.getConfig("site"):
c+=a.getConfig("site");return t(c)};this.cacheInvalidation=function(){b={}}};window.ATInternet.Tracker.Tag.prototype.addPlugin("Cookies");
}).call(window);;(function(){var dfltPluginCfg={"lifetime":182,"domainAttribution":true,"info":"True"};var dfltGlobalCfg={"redirectionLifetime":30};window.ATInternet.Tracker.Plugins.IdentifiedVisitor=function(a){var b=null,h=null,g=null,k=null,d="",f="",e=null,c=null,l="",n="",t={};a.configPlugin("IdentifiedVisitor",dfltPluginCfg||{},function(a){t=a});a.setConfig("redirectionLifetime",dfltGlobalCfg.redirectionLifetime,!0);var r=function(c,b,d){var e=null;a.plugins.exec(c,b,d,function(a){e=a});return e},p=function(a,c){return r("Utils",a,c)},s=function(c,b){var d=null;a.plugins.exec("Cookies",c,b,function(a){d=a});return d},q=function(a,c){var b=
s(n,[[a]]);if(null!==b)return!("object"!==typeof b||b instanceof Array);s(l,[a,{},c]);return!0},E=function(){var l=function(a,c){/-/.test(c)?(a.category=c.split("-")[0],a.id=c.split("-")[1]):a.id=c},q={category:"",id:""};l(q,f||c);var n={category:"",id:""};l(n,d||e);n.id?(n.category&&w("ac",n.category),w("at",n.id)):b&&a.setParam("at",b,{typeHit:["all"],permanent:!0});q.id?(q.category&&w("ac",q.category),w("an",q.id)):h&&a.setParam("anc",g+"-"+h,{typeHit:["all"],permanent:!0})},w=function(c,b){a.setParam(c,
b,{typeHit:["all"],permanent:!0});v(c,b)},v=function(a,c){q("atidvisitor",{path:"/",session:86400*t.lifetime})&&s(l,[["atidvisitor",a],c])};a.plugins.waitForDependencies(["Cookies","Utils"],function(){l="set"+(t.domainAttribution?"":"Private");n="get"+(t.domainAttribution?"":"Private");var w=p("getLocation",[]);d=p("getQueryStringValue",["xtat",w]);f=p("getQueryStringValue",["xtan",w]);a.getConfig("redirect")?(d||f)&&q("atredir",{path:"/",end:a.getConfig("redirectionLifetime")})&&(f&&s(l,[["atredir",
"an"],f]),d&&s(l,[["atredir","at"],d])):(e=s(n,[["atredir","at"]]),c=s(n,[["atredir","an"]]),s("del",[["atredir","at"]]),s("del",[["atredir","an"]]),b=s(n,[["atidvisitor","at"]]),h=s(n,[["atidvisitor","an"]]),g=s(n,[["atidvisitor","ac"]]),k=s(n,[["atidvisitor","vrn"]]),E(),w="-"+a.getConfig("site")+"-",RegExp(w).test(k)||(k=(k||"")+w,v("vrn",k),w=a.getContext("page")||{},w.vrn=1,a.setContext("page",w)))});a.identifiedVisitor={};a.identifiedVisitor.set=this.set=function(a){var c=a.id;a=a.category;
"number"===typeof c?w("an",c.toString()):w("at",c);"undefined"!==typeof a&&w("ac",a)};a.identifiedVisitor.unset=this.unset=function(){for(var c=["an","at","ac"],b=0;b<c.length;b++)a.exec("Cookies","set",[["atidvisitor",c[b],{path:"/"}],void 0]),a.delParam(c[b]);a.delParam("anc")}};window.ATInternet.Tracker.Tag.prototype.addPlugin("IdentifiedVisitor");
}).call(window);;(function(){var dfltPluginCfg={"urlKeyword":"","urlResultPageNumber":"","urlResultPosition":"","info":"True"};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.InternalSearch=function(a){var b={};a.configPlugin("InternalSearch",dfltPluginCfg||{},function(a){b=a});a.internalSearch={};a.internalSearch.set=this.set=function(b){a.setContext("InternalSearch",{keyword:b.keyword,resultPageNumber:b.resultPageNumber})};a.internalSearch.send=this.send=function(b){var g=!0;a.plugins.exec("TechClicks","manageClick",[b.elem],function(a){g=a});a.sendHit({mc:b.keyword,np:b.resultPageNumber||0,mcrg:b.resultPosition||"",click:"IS"},[["typeHit",
["InternalSearch"]]]);return g};a.plugins.waitForDependencies(["Utils"],function(){var h;if(b.urlKeyword){var g=document.location.href;h={};a.plugins.exec("Utils","getQueryStringValue",[b.urlKeyword,g],function(k){h.keyword=k;b.urlResultPageNumber&&a.plugins.exec("Utils","getQueryStringValue",[b.urlResultPageNumber,g],function(d){h.resultPageNumber=d;b.urlResultPosition&&a.plugins.exec("Utils","getQueryStringValue",[b.urlResultPosition,g],function(a){h.resultPosition=a})})})}h&&a.setContext("InternalSearch",
h)})};window.ATInternet.Tracker.Tag.prototype.addPlugin("InternalSearch");
}).call(window);;(function(){var dfltPluginCfg={"info":"True"};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.OnSiteAds=function(a){var b="",h=!1,g=function(c){var b=c.name;a.exec("Utils","manageChapters",[c,"chapter",3],function(a){b=a+(b?b:"")});return b},k=function(a){h&&a()},d=function(a,c){return a[c]?a[c]:""},f=function(a,c){var b=d(a,c);if(b){var e=d(a,"prefix");if(b.campaignId){var e=e||"PUB",f=d(b,"campaignId"),l=d(b,"creation"),n=d(b,"variant"),g=d(b,"format"),h=d(b,"generalPlacement"),k=d(b,"detailedPlacement"),t=d(b,"advertiserId"),b=d(b,"url");return e+"-"+f+
"-"+l+"-"+n+"-"+g+"-"+h+"-"+k+"-"+t+"-"+b}if(b.adId)return e=e||"INT",f=d(b,"adId"),g=d(b,"format"),b=d(b,"productId"),e+"-"+f+"-"+g+"||"+b}},e=function(c){var b=a.getContext("page")||{};a.sendHit({atc:f(c,"click"),type:"AT",patc:g(b),s2atc:b.level2||"",stc:c.customObject||""},[["typeHit",["onSiteAdsClick"]]])},c=function(c){a.sendHit({ati:f(c,"impression"),type:"AT",stc:c.customObject||""},[["typeHit",["onSiteAdsImpression"]]])},l=function(c,b){var d=a.buffer.get("ati",!0)||{};d.value="string"===
typeof d.value?[d.value]:d.value||[];d.options=d.options||{typeHit:[b,"page"]};d.value.push(c);a.buffer.set("ati",d.value,d.options)},n=function(a,c,b){k(b)},t=function(c,b){c.click?a.setParam("atc",f(c,"click"),{typeHit:[b,"page"]}):c.impression&&a.setParam("ati",f(c,"impression"),{typeHit:[b,"page"]});if(c.customObject){a.setContext("onsiteads",{customObject:c.customObject});var d=a.getContext("page")||{};d.customObject=ATInternet.Utils.completeFstLevelObj(d.customObject,c.customObject,!1);a.setContext("page",
d)}a.dispatchSubscribe("onSiteAds")};a.selfPromotion=this.selfPromotion={};a.publisher=this.publisher={};a.publisher.set=this.publisher.set=function(a){n("publisher:set",a,function(){t(a,"publisher")})};a.selfPromotion.set=this.selfPromotion.set=function(a){n("selfPromotion:set",a,function(){t(a,"selfPromotion")})};a.publisher.add=this.publisher.add=function(c){n("publisher:add",c,function(){l(f(c,"impression"),"publisher");a.dispatchSubscribe("onSiteAds")})};a.selfPromotion.add=this.selfPromotion.add=
function(c){n("selfPromotion:add",c,function(){l(f(c,"impression"),"selfPromotion");a.dispatchSubscribe("onSiteAds")})};var r=this.advertEvent=function(b){var d=!0;k(function(){a.exec("TechClicks","manageClick",[b.elem],function(a){d=a});b.click?e(b):b.impression&&c(b)});return d};a.publisher.send=this.publisher.send=function(a){return r(a)};a.selfPromotion.send=this.selfPromotion.send=function(a){return r(a)};a.onSiteAds={};a.onSiteAds.onDispatch=this.onDispatch=function(){if(!a.dispatchSubscribed("page")){var c=
a.getContext("page")||{};a.setParam("type","AT",{typeHit:["publisher","selfPromotion"]});a.getParam("atc")&&(a.setParam("patc",g(c),{typeHit:["publisher","selfPromotion"]}),a.setParam("s2atc",c.level2||"",{typeHit:["publisher","selfPromotion"]}));(c=a.getContext("onsiteads"))&&c.customObject&&a.setParam("stc",c.customObject,{encode:!0,typeHit:["publisher","selfPromotion"]});a.sendHit(null,[["typeHit",["publisher","selfPromotion"]]])}};a.plugins.waitForDependencies(["Utils","TechClicks"],function(){h=
!0;b=document.location.href;a.plugins.exec("Utils","getQueryStringValue",["xtatc",b],function(c){c&&a.setParam("atc",c,{typeHit:["publisher","selfPromotion","page"]})})})};window.ATInternet.Tracker.Tag.prototype.addPlugin("OnSiteAds");
}).call(window);;(function(){var dfltPluginCfg={"info":"True"};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.Page=function(a){var b=["pageId","chapterLabel","update"],h=["pid","pchap","pidt"],g=["page","site"],k=["f","x"],d=function(c){var b=c.name;a.exec("Utils","manageChapters",[c,"chapter",3],function(a){b=a+(b?b:"")});return b},f=function(a,c,b){c?a=c:a||"undefined"===typeof b||(a=b);return a},e=function(a,c,b){c.hasOwnProperty(b)&&(a[b]=f(a[b],c[b]))},c=function(c){if(!ATInternet.Utils.isPreview()||a.getConfig("preview"))ATInternet.Utils.isPrerender(function(a){c(a)})||
c()},l=function(c,b,d){if(b)for(var e=0;e<g.length;e++)if(b.hasOwnProperty(g[e])&&b[g[e]])for(var f in b[g[e]])b[g[e]].hasOwnProperty(f)&&(d?c[k[e]+f]=b[g[e]][f]:a.setParam(k[e]+f,b[g[e]][f]))},n=function(c,d,e){if(d){a.exec("Utils","manageChapters",[d,"chapter",3],function(a){a&&(d.chapterLabel=a.replace(/::$/gi,""))});for(var f=0;f<h.length;f++)d.hasOwnProperty(b[f])&&(e?c[h[f]]=d[b[f]]:a.setParam(h[f],d[b[f]]))}},t=function(c,b,d){if(b&&b.keywords instanceof Array){var e=b.keywords.length;if(0<
e){for(var f="",g=0;g<e;g++)f+="["+b.keywords[g]+"]"+(g<e-1?"|":"");d?c.tag=f:a.setParam("tag",f)}}},r=function(c,b,d){if(b){var e,f=function(a){return a?a:"0"};e=""+(f(b.category1)+"-");e+=f(b.category2)+"-";e+=f(b.category3);d?c.ptype=e:a.setParam("ptype",e)}},p=function(c,b,d){if(b)for(var e in b)b.hasOwnProperty(e)&&"undefined"!==typeof b[e]&&(d?c[e]=b[e]:a.setParam(e,b[e]))};a.customVars=this.customVars={};a.customVars.set=this.customVars.set=function(c){var b=a.getContext("page")||{},d=b.customVars;
if(d){if(c)for(var e in c)c.hasOwnProperty(e)&&(d[e]=ATInternet.Utils.completeFstLevelObj(d[e],c[e],!0))}else d=c;b.customVars=d;a.setContext("page",b)};a.dynamicLabel=this.dynamicLabel={};a.dynamicLabel.set=this.dynamicLabel.set=function(c){var b=a.getContext("page")||{};b.dynamicLabel=ATInternet.Utils.completeFstLevelObj(b.dynamicLabel,c,!0);a.setContext("page",b)};a.tags=this.tags={};a.tags.set=this.tags.set=function(c){var b=a.getContext("page")||{};b.tags=ATInternet.Utils.completeFstLevelObj(b.tags,
c,!0);a.setContext("page",b)};a.customTreeStructure=this.customTreeStructure={};a.customTreeStructure.set=this.customTreeStructure.set=function(c){var b=a.getContext("page")||{};b.customTreeStructure=ATInternet.Utils.completeFstLevelObj(b.customTreeStructure,c,!0);a.setContext("page",b)};a.page={};a.page.reset=this.reset=function(){a.setContext("page",void 0)};a.page.set=this.set=function(c){a.dispatchSubscribe("page");var b=a.getContext("page")||{};b.name=f(b.name,c.name,"");b.level2=f(b.level2,
c.level2,"");e(b,c,"chapter1");e(b,c,"chapter2");e(b,c,"chapter3");b.customObject=ATInternet.Utils.completeFstLevelObj(b.customObject,c.customObject,!0);a.setContext("page",b)};a.page.send=this.send=function(b){var g={p:d(b),s2:b.level2||""},h=!0,k=b.customObject;if(k){var v=a.getParam("stc",!0);if(v&&v.options.permanent){var u=v?v.options.typeHit:[],A=ATInternet.Utils.arrayIndexOf;if(-1!=A(u,"page")||-1!=A(u,"all"))k=ATInternet.Utils.completeFstLevelObj(v.value||{},k,!0)}a.exec("Utils","customObjectToString",
[k],function(a){g.stc=a})}k=a.getContext("page")||{};k.vrn&&(g.vrn=k.vrn,k.vrn=void 0,a.setContext("page",k));v=a.getContext("InternalSearch")||{};"undefined"!=typeof v.keyword&&(g.mc=ATInternet.Utils.cloneSimpleObject(v.keyword),"undefined"!=typeof v.resultPageNumber&&(g.np=ATInternet.Utils.cloneSimpleObject(v.resultPageNumber)),"undefined"!=typeof v.resultPosition&&(g.mcrg=ATInternet.Utils.cloneSimpleObject(v.resultPosition)),a.setContext("InternalSearch",void 0));ATInternet.Utils.isPreview()&&
a.getConfig("preview")&&(g.pvw=1);l(g,b.customVars,!0);n(g,b.dynamicLabel,!0);t(g,b.tags,!0);r(g,b.customTreeStructure,!0);v=a.getContext("campaigns")||{};p(g,v,!0);a.setContext("campaigns",void 0);a.exec("TechClicks","manageClick",[b.elem],function(a){h=a});c(function(){a.sendHit(g)});k.name=f(k.name,b.name,"");k.level2=f(k.level2,b.level2,"");e(k,b,"chapter1");e(k,b,"chapter2");e(k,b,"chapter3");a.setContext("page",k);return h};a.page.onDispatch=this.onDispatch=function(){var b=a.getContext("page")||
{},e=a.getContext("InternalSearch")||{};a.setParam("p",d(b));a.setParam("s2",b.level2||"");b.vrn&&(a.setParam("vrn",b.vrn),b.vrn=void 0,a.setContext("page",b));"undefined"!=typeof e.keyword&&(a.setParam("mc",ATInternet.Utils.cloneSimpleObject(e.keyword)),"undefined"!=typeof e.resultPageNumber&&a.setParam("np",ATInternet.Utils.cloneSimpleObject(e.resultPageNumber)),"undefined"!=typeof e.resultPosition&&a.setParam("mcrg",ATInternet.Utils.cloneSimpleObject(e.resultPosition)),a.setContext("InternalSearch",
void 0));ATInternet.Utils.isPreview()&&a.getConfig("preview")&&a.setParam("pvw",1);l(null,b.customVars,!1);n(null,b.dynamicLabel,!1);t(null,b.tags,!1);r(null,b.customTreeStructure,!1);e=a.getContext("campaigns")||{};p(null,e,!1);a.setContext("campaigns",void 0);var b=b.customObject,f=[["typeHit",["page"]]];if(b)if(e=a.getParam("stc",!0)){var g=e.options.typeHit||[],h=ATInternet.Utils.arrayIndexOf,h=-1!=h(g,"page")||-1!=h(g,"all"),g=e.options.permanent;h?(h=ATInternet.Utils.cloneSimpleObject(e),h.value=
ATInternet.Utils.completeFstLevelObj(h.value||{},b,!0),a.setParam("stc",h.value,{encode:!0}),c(function(){a.sendHit(null,f)}),g&&a.setParam("stc",e.value,e.options)):(a.setParam("stc",b,{encode:!0}),c(function(){a.sendHit(null,f)}),a.setParam("stc",e.value,e.options))}else a.setParam("stc",b,{encode:!0}),c(function(){a.sendHit(null,f)});else c(function(){a.sendHit(null,f)})}};window.ATInternet.Tracker.Tag.prototype.addPlugin("Page");
}).call(window);;(function(){var dfltPluginCfg={"clicksAutoManagementEnabled":true,"clicksAutoManagementTimeout":500,"info":"False"};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.TechClicks=function(a){var b,h;a.configPlugin("TechClicks",dfltPluginCfg||{},function(a){b=a.clicksAutoManagementEnabled;h=a.clicksAutoManagementTimeout});this.deactivateAutoManagement=function(){b=!1};var g=function(a){switch(a.target){case "_top":window.top.location.href=a.url;break;case "_parent":window.parent.location.href=a.url;break;default:window.location.href=a.url}},k=function(a){var c=a.timeout;a.mailto?setTimeout(function(){window.location.href=a.mailto},
c):a.form?setTimeout(function(){a.form.submit()},c):a.url&&setTimeout(function(){g({url:a.url,target:a.target})},c)},d=function(c){for(var b,d="_self",e=c.timeoutonly;c;){if(c.href&&0===c.href.indexOf("http")){b=c.href.split('"').join('\\"');d=c.target?c.target:d;break}c=c.parentNode}if(b){if(!e)a.onTrigger("Tracker:Hit:Sent:Ok",function(){g({url:b,target:d})});k({url:b,target:d,timeout:h})}},f=function(c){var b=c;for(c=b.timeoutonly;b&&"FORM"!==b.nodeName;)b=b.parentNode;if(b){if(!c)a.onTrigger("Tracker:Hit:Sent:Ok",
function(){b.submit()});k({form:b,timeout:h})}},e=function(c){var b=c;for(c=b.timeoutonly;b&&!(b.href&&0<=b.href.indexOf("mailto:"));)b=b.parentNode;if(b){if(!c)a.onTrigger("Tracker:Hit:Sent:Ok",function(){window.location.href=b.href});k({mailto:b.href,timeout:h})}},c=function(a){for(;a;){if(a.href){if(0<=a.href.indexOf("mailto:"))return"mailto";if(0===a.href.indexOf("http"))return"redirection"}else if("FORM"===a.nodeName)return"form";a=a.parentNode}return!1};this.manageClick=function(a,g){if(b&&
a){var h;a:{for(h=a;h;){if("function"===typeof h.getAttribute&&("_blank"===h.getAttribute("target")||"no"===h.getAttribute("data-atclickmanagement"))){h=!0;break a}h=h.parentNode}h=a;for(var k=window.location.href,p;h;){if((p=h.href)&&0<p.indexOf("#")&&k.substring(0,0<k.indexOf("#")?k.indexOf("#"):k.length)===p.substring(0,p.indexOf("#"))){h=!0;break a}h=h.parentNode}h=!1}k=c(a);if(!h&&k){switch(k){case "mailto":e(a);break;case "form":f(a);break;case "redirection":d(a);break;default:return!0}g&&!g.defaultPrevented&&
g.preventDefault();return!1}}return!0}};window.ATInternet.Tracker.Tag.prototype.addPlugin("TechClicks");
}).call(window);;(function(){var dfltPluginCfg={"info":"False"};var dfltGlobalCfg={};(function(){window.ATInternet.Tracker.Plugins.Utils=function(a){var b=this,h={};b.getQueryStringValue=function(a,b){var d=window.ATInternet.Utils.hashcode(b).toString();if(!h[d]){h[d]={};var f=RegExp("[&#?]{1}([^&=#?]*)=([^&#]*)?","g"),e=f.exec(b);if(null!==e)for(;null!==e;)h[d][e[1]]=e[2],e=f.exec(b)}return h[d].hasOwnProperty(a)?h[d][a]:null};b.customObjectToString=function(a){return encodeURIComponent(window.ATInternet.Utils.jsonSerialize(a))};b.manageChapters=function(a,b,d){var f="";if(a){d=
parseInt(d,10);for(var e=1;e<d+1;e++)a.hasOwnProperty(b+e)&&(f+=(a[b+e]||"")+"::")}return f};b.getDocumentLevel=function(){return window[a.getConfig("documentLevel")]||document};b.getLocation=function(){return b.getDocumentLevel().location.href};a.dispatchIndex={};a.dispatchStack=[];a.dispatchSubscribe=function(b){return a.dispatchIndex[b]?!1:(a.dispatchStack.push(b),a.dispatchIndex[b]=!0)};a.dispatchSubscribed=function(b){return!0===a.dispatchIndex[b]};a.dispatch=function(){var b=function(b,d){for(;0<
a.dispatchStack.length;){var f=a.dispatchStack.pop();a[f].onDispatch()}a.dispatchIndex={};a.delContext(void 0,"customObject")};if(a.plugins.isExecWaitingLazyloading())a.onTrigger("Tracker:Plugin:Lazyload:Exec:Complete",function(a,d){b(a,d)},!0);else b()};a.dispatchRedirect=function(b){var h=!0;b&&b.elem&&(b.elem.timeoutonly=!0,a.plugins.exec("TechClicks","manageClick",[b.elem],function(a){h=a}));a.dispatch();return h}};window.ATInternet.Tracker.Tag.prototype.addPlugin("Utils")}).call(window);
}).call(window);
if(typeof window.ATInternet.onTrackerLoad==='function'){window.ATInternet.onTrackerLoad();}