window.log=function(){log.history=log.history||[];log.history.push(arguments);if(this.console){arguments.callee=arguments.callee.caller;var a=[].slice.call(arguments);(typeof console.log==="object"?log.apply.call(console.log,console,a):console.log.apply(console,a))}};
(function(b){for(var d="assert,count,debug,dir,dirxml,error,exception,group,groupCollapsed,groupEnd,info,log,timeStamp,profile,profileEnd,time,timeEnd,trace,warn".split(","),a;a=d.pop();){if(b[a]){b[a]=b[a]}else{b[a]=function(){}}}})((function(){try{return window.console;}catch(err){return window.console={};}})());!function(a){"use strict";var s=a.Obs;a.domready(function(){var a=s("#sas_21486");a&&s.hasClass(a,"js-has-ad")&&s.addClass(s("#habillagepub"),"has-habillage")})}(this);;

!function(e){"use strict";function t(){if(s.get(m)){if(!u){var e=l("#template-encart-abo");if(!e)return;v=document.createElement("div"),v.innerHTML=e.innerHTML}}else{var t=l("#template-encart-newsletter");if(!t)return;v=document.createElement("div"),v.innerHTML=t.innerHTML}i[3]&&i[3].parentNode.insertBefore(v,i[3].nextSibling)}function n(t){if(t){var n=t.querySelector('script[type*="ad"]');if(n){var r=n.innerHTML,i=new Function(r);i.call(e)}}}function r(){return self.innerWidth?self.innerWidth:document.documentElement&&document.documentElement.clientWidth?document.documentElement.clientWidth:document.body?document.body.clientWidth:void 0}var i=[],l=e.Obs,a=e.Premium||null,s=e.ObsCookie,d="#js-article-body",o=l(d);o&&(i=o.querySelectorAll(d+">p"));var c=l(".colonne-article-zone");if(i.length>=5){var m="article-bloc-newsletter",u=!1,v=null;a?a.Consumer.on("update",function(e){e&&e.freemium&&(u=!0),t()}):t();var f=l(".encart-newsletter-close");f&&f.length&&f[0].addEventListener("click",function(){l(".encart-newsletter")[0].style.display="none";var e=new Date;e=new Date(e.getTime()+2592e6),s.set(m,1,e.toUTCString(),"_all")});var b=l(".encart-newsletter");b&&b.length&&(b=b[0],l("#encart-newsletter-submit").addEventListener("click",function(e){return e.preventDefault(),0==document.getElementById("encart-newsletter-email").value.length?(l.addClass(b,"sent-error"),void(l(".message-error")[0].innerHTML="Merci d'indiquer une adresse email.")):(l("#encart-newsletter-submit").disabled=!0,l("#encart-newsletter-submit").setAttribute("disabled","disabled"),l.removeClass(b,"sent-ok"),l.removeClass(b,"sent-error"),void l.ajax("/newsletter/inscript_async.json",{type:"POST",dataType:"json",data:{themes_select:document.getElementById("encart-newsletter-theme").value,email:document.getElementById("encart-newsletter-email").value}}).then(function(){l.addClass(b,"sent-ok");var e=new Date;e.setYear(e.getFullYear()+1),s.set(m,1,e.toUTCString(),"_all"),xt_med("C",xtn2,"Divers_Articles::::"+xtpage+"::_S_Inscrire_NL","A")})["catch"](function(e){l.addClass(b,"sent-error"),"email"==e.detail?l(".message-error")[0].innerHTML="Cette adresse email est invalide.":l(".message-error")[0].innerHTML="Une erreur est survenue. Merci de réessayer."})["finally"](function(){l("#encart-newsletter-submit").disabled=!1,l("#encart-newsletter-submit").removeAttribute("disabled")}))}))}var g=l("#template-article-insert-pub-1"),h=l("#template-article-insert-pub-2");r()<800?(l.removeClass(c[0],"scrolling"),l.removeClass(c[0],"hidden"),l.removeClass(c[1],"scrolling"),l.removeClass(c[1],"hidden"),l.removeClass(c[2],"scrolling"),l.removeClass(c[2],"hidden"),g&&(i.length>=12?(v=document.createElement("div"),v.innerHTML=g.innerHTML,g.remove(),n(i[7].appendChild(v))):g.remove()),h&&(i.length>=20?(v=document.createElement("div"),v.innerHTML=h.innerHTML,h.remove(),n(i[15].appendChild(v))):h.remove())):(g&&g.remove(),h&&h.remove())}(this);;

!function(s){"use strict";var e=s.Obs,t=e(".share-autres");t&&t.length>0&&t[0].addEventListener("click",function(){e.removeClass(e(".share-compteurs")[0],"closed"),this.style.display="none"})}(this);;

!function(e){"use strict";function t(){if("undefined"!=typeof window.getSelection){var t=window.getSelection().toString();if(t.length>0){var n=window.getSelection().getRangeAt(0).getBoundingClientRect(),i=Math.ceil(o.top(d)-o.top(document.body)),l=52;o.removeClass(s,"hidden"),s.style.top=e.pageYOffset+n.top-i-l+"px",s.style.left=Math.ceil(Math.abs(o.left(d)-n.left)+n.width/2-o.width(s)/2)+"px",t=encodeURI(t),o.attr(a[0],"href",o.attr(a[0],"data-href")+t)}else o.addClass(s,"hidden")}else o.addClass(s,"hidden")}function n(){if("undefined"==typeof window.getSelection)return o.addClass(s,"hidden"),null;var e=window.getSelection().toString();0==e.length&&o.addClass(s,"hidden")}var o=e.Obs,i=o("#js-article-body"),d=o("#obs-container"),s=o("#js-text-select-sharing"),a=o(".js-share-button",s);i&&(i.onmouseup=function(){setTimeout(t,0)},i.onkeyup=function(){setTimeout(t,0)},document.onmouseup=n,document.onkeyup=n)}(this);;

!function(t){"use strict";var e=t.Obs,o=t.ObsCookie,s=e(".zoomer"),a=e("#js-article-body");if(s&&s.length>0&&a){var i=o.get("article-text-zoom")||2,r=i;e.addClass(a,"text-zoom-"+i),s[0].addEventListener("click",function(){r=i,i++,i>4&&(i=1),o.set("article-text-zoom",i),e.removeClass(a,"text-zoom-"+r),e.addClass(a,"text-zoom-"+i)})}}(this);;

!function(e){"use strict";var r=e.Obs,t=r(".js-share-button");for(var n in t)t.hasOwnProperty(n)&&t[n].addEventListener("click",function(e){return e.preventDefault(),window.open(this.href,"","menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600"),!1})}(this);;

!function(t){"use strict";var c=t.Obs,i=c(".lire");c.forEach(i,function(t,i){c.attr(t,"onclick","xt_med('C', xtn2, 'Recirculation_Articles::Corps::Liens_Corps::"+(i+1)+"', 'N')")});var n=c(".a-chaud");n[0]&&bean.on(n[0],"click","a",function(){xt_med("C",xtn2,"Recirculation_Articles::Colonne_De_Droite::A_Chaud","N")})}(this);;

!function(e){"use strict";var t=e.document,a=e.Obs;e.HTMLElement.prototype.wrap=function(e){e.length||(e=[e]);for(var t=e.length-1;t>=0;t--){var a=t>0?this.cloneNode(!0):this,r=e[t],n=r.parentNode,o=r.nextSibling;a.appendChild(r),o?n.insertBefore(a,o):n.appendChild(a)}},a.embed=function(e,r,n){if(e){var o=["e\\.infogr\\.am","youscribe\\.com","piktochart\\.com","concours\\.challenges.fr","instagram\\.com","soundcloud\\.com","embed\\.gettyimages\\.com","scribd\\.com","imgur\\.com","widget\\.beopinion\\.com"],i=o.concat(r||[]).join("|"),c=new RegExp("("+i+")","i");return a.isDomNode(e)&&(e=[e]),n=n||"embed-container",a.forEach(e,function(e){var r="iframe",o="embed",i="object",s="width",d="height",m=e.querySelectorAll([r,i,o].join(","));a.forEach(m,function(e){var m=a.attr(e,"src"),l=e.tagName.toLowerCase();if(!(l===r&&!m||l===o&&a.parent(e,"="+i)||c.test(m)||a.parent(e,"."+n))){var p=a.attr(e,d),h=a.attr(e,s),u=p&&!isNaN(parseInt(p,10))?parseInt(p,10):a.height(e),g=isNaN(parseInt(h,10))?a.width(e):parseInt(h,10);e.removeAttribute("style");var f=t.createElement("div");f.className=n,f.style.paddingBottom=u/g*100+"%",a.attr(e,d,null),a.attr(e,s,null),e.parentNode.appendChild(f),a.addClass(e.parentNode,"has-embed"),f.wrap(e)}})})}}}(this);;

!function(s){"use strict";var t=s.Obs;t.embed(t("#js-article-body"))}(this);;

!function(e,t){"use strict";e.domready(function(){var a=e.Obs,r=e.document;t.on(r.body,"click",".js-live-share",function(e){for(var r=this;r.parentNode&&"li"!=r.parentNode.nodeName.toLowerCase();)if(r=r.parentNode,"body"==r.nodeName.toLowerCase())return;a.addClass(r.parentNode,"live-activ"),t.one(a(".close",r.parentNode)[0],"click",function(e){a.removeClass(r.parentNode,"live-activ"),e.stop()}),e.stop()}),a.loadPostEmbed=function(t){try{switch(a.attr(t,"data-embedName")){case"twitter":twttr&&twttr.widgets&&twttr.widgets.load();break;case"instagram":instgrm&&instgrm.Embeds.process();break;case"infogram":e.InfogramEmbed?InfogramEmbed.load():function(){var e=r.createElement("script");e.src=a.attr(a("script",el)[0],"src"),r.body.appendChild(e)}()}}catch(o){}}})}(this,bean);;

